version: '3.7'
services: 
  proxy:
    image: bitnami/envoy
    volumes: 
      - ./envoy/envoy.yaml:/opt/bitnami/envoy/conf/envoy.yaml
    ports:
      - "8080:8080"
      - "8001:8001"
    networks:
      - envoymesh
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    networks: 
      - teastore
    environment:
      HOST_NAME: "registry"
      SERVICE_PORT: "8080"
  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks: 
      - teastore
  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    networks: 
      - teastore
  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    networks: 
      - teastore
  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    networks: 
      - teastore
  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    networks: 
      - teastore
  webui:
    image: descartesresearch/teastore-webui
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      SERVICE_PORT: "3000"
      PROXY_NAME: "proxy"
      PROXY_PORT: "8080"
    networks: 
      - envoymesh
      - teastore
networks:
  envoymesh: {}
  teastore: {}