{
 "title": "Envoy Service Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "envoy_cluster_name",
    "label": "Destination Service",
    "query": "label_values(envoy_cluster_version, envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Total Connections / Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_membership_change{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "membership changes [1m]"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "total membershiip"
    },
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "outlier ejections active"
    },
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "healthy members (active HC and outlier)"
    },
    {
     "expr": "sum(envoy_cluster_health_check_healthy{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "healthy members (active HC only)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",envoy_cluster_name=~\"$envoy_cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "Success Rate %"
    }
   ]
  },
  {
   "title": "4xx %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=~\"$envoy_cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Upstream Request Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{instance=~\"[[originating_instance]]\",local_cluster=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{instance=~\"[[originating_instance]]\",local_cluster=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{instance=~\"[[originating_instance]]\",local_cluster=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{instance=~\"[[originating_instance]]\",local_cluster=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{instance=~\"[[originating_instance]]\",local_cluster=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Request Retry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Upstream Flow Control Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "paused reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "resumed reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "paused reading from originating service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "resumed reading from originating service"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
     "legendFormat": "50th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
     "legendFormat": "99th %ile"
    }
   ]
  },
  {
   "title": "retry overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "overflows"
    }
   ]
  },
  {
   "title": "connection overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{envoy_cluster_name=\"$envoy_cluster_name\"})"
    }
   ]
  },
  {
   "title": "request overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "overflows"
    }
   ]
  },
  {
   "title": "request overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"$envoy_cluster_name\"})"
    }
   ]
  },
  {
   "title": "connection overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{envoy_cluster_name=\"$envoy_cluster_name\"})"
    }
   ]
  }
 ]
}