{
 "title": "Envoy global",
 "time": { "from": "2020-11-24T22:46:12.482Z", "to": "2020-11-24T22:56:12.482Z" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_health_check_attempt[1m]))",
     "legendFormat": "Global HC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total[1m]))",
     "legendFormat": "Total Ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow[1m]))",
     "legendFormat": "Total Ejection Overflows"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(envoy_cluster_health_check_success[1m])) / sum(rate(envoy_cluster_health_check_attempt[1m]))))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Max Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(envoy_server_version)" }
   ]
  },
  {
   "title": "Min Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(envoy_server_version)" }
   ]
  }
 ]
}